# 숫자야구게임
# 컴퓨터가 랜덤으로 1~9 사이의 임의의 숫자를 3개 생성
# 사용자로부터 1~9 사이의 중복 없는 3자리 숫자를 입력받기
# ex) 456 == 임의의 숫자를 3개와 비교 = 3개의 숫자를 위치까지 다 맞췄다면 3스트라이크
# 위치 상관없이 2개만 맞췄다면 0스트라이크 2볼
# q를 입력하기 전까지는 계속 반복
# 3스트라이크가 나오면 반복문 중단

# import random

# numbers = [1,2,3,4,5,6,7,8,9]
# def make_answer():
#     '''1~9 중 중복없는 3자리 숫자 생성'''
#     return random.sample(numbers,3)

# # 숫자입력받기
# user_num1 = input('press num1')
# user_num2 = input('press num2')
# user_num3 = input('press num3')

# guess=[user_num1,user_num2,user_num3]
# answer=make_answer()

# def get_strike_ball(answer,guess):
#     '''답변하고 응답하고 비교 후 strike값, ball값 리턴'''
#     # 답변하고 응답값 비교
#     if guess[0,1,2] == answer[0,1,2]:
#         return print('3 strike')
#         # 답변하고 응답값 비교 : 2개만 맞췄을때
#     elif guess:
#         pass
#      # 답변하고 응답값 비교 : 1개만 맞췄을때 
#     elif guess:
#         pass
#     # 다 틀렸을때
#     else:
#         print('NT')



# 답지
import random
import time
def make_answer():
    '''1~9 중 중복없는 3자리 숫자 생성'''
    return random.sample(range(1,10),k=3)

def get_strike_ball(answer,guess):
    '''답변하고 응답하고 비교 후 strike값, ball값 리턴'''
    strike, ball =0,0
    for i in range(3):
        if guess[i] == answer[i]:
            strike+=1
        elif guess[i] in answer:
            ball+=1
    return strike, ball



# 정답(숫자 3개) 리스트 생성
answer = make_answer()
# 시도횟수
attempts = 0
# 프로그램 중단 여부
is_quit = False

print("=== NUMBER BASEBALL GAME===")
print("1~9 사이 중복 없는 3자리 숫자를 맞춰 보세요.")

import time
start = time.time()
while True:
    # 사용자로부터 숫자 3개 입력받기
    guess_input = input("press nums (ex:123)").strip()

    if guess_input.lower() == "q":
        print("Quit Game")
        is_quit = True
        break

    # 3자리가 맞는지 확인, 숫자가 맞는지 확인
    if len(guess_input) != 3 or not guess_input.isdigit():
        print("press nums")
        continue # 다시 올라가서 숫자 입력받는 구문

    # input 값을 리스트에 담는 구문 ex: answer=[1,2,3], guess=[123]
    #  방법 1 .guess = []
    #         for ch in guess_input:
    #         guess.append(int(ch))
    guess = [int(ch) for ch in guess_input]

    attempts += 1

    strike, ball = get_strike_ball(answer,guess)

    if strike ==3:
        print(f"Correct! {strike}Strike")
        break
    else:
        print(f"{strike}Strike {ball}Ball")



end = time.time()
# 걸린 시간
elapsed = format(end-start, ".3f")
print(f"tried {attempts}, time : {elapsed}sec")

# 중간에 종료했다면 기록을 남기지 말고 프로그램 종료
if is_quit:
    exit()





# 오라클 연동
# bassball_record 테이블 생성
# record_id 자동증가, 소요 시간, 게임 일자, 시도 횟수
import oracledb
from dotenv import load_dotenv

with oracledb.connect(user="python_user",password="54321",dsn="localhost/xe") as conn:
    with conn.cursor() as cursor:
        # record_id : 자동증가 컬럼
        try:
            sql = """create table baseball_records(
            record_id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attempts number,
            elapsed varchar2(20),
            regdate date
            )
            """
            cursor.execute(sql)
        except oracledb.DatabaseError as e:
            (error_obj,) = e.args
            if error_obj.code == 955:
                print(error_obj.message)
            else:
                raise

        # insert 작업(기록 삽입)
        from datetime import datetime
        now = datetime.now()
        nowDateTime = now.strftime("%Y-%m-%d %H:%M:%S")
        sql = "insert into baseball_records(attempts,elapsed,regdate) values(:1,:2,sysdate)"
        cursor.execute(sql,(attempts,elapsed))
        conn.commit()

print("기록이 저장되었습니다.")    