import random
import oracledb
import time


sentences = [
    "THe quick brown fox jumps over the lazy dog",
    "Python is a powerful programming language",
    "Practice makes perfect every single day",
    "Oracle database stores data reliably",
    "Typing speed improves with daily practice",
    ]

conn = oracledb.connect(user="PYTHON_USER",password="54321",dsn="localhost/XE")
cursor = conn.cursor()

# create table
try:
    sql = """create table typing_records(
            record_id number(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            elapsed varchar2(20) not null,
            accuracy varchar2(20) not null,
            regdate_date date default sysdate
            )
            """
    cursor.execute(sql)
except oracledb.DatabaseError as e:
    (error_obj,) = e.args
    if error_obj.code == 955:
        print(error_obj.message)
    else:
        raise



# random.sample(sentences,k=1) 무작위로 한 개 추출 방법 1
target = random.choices(sentences) # 무작위로 한 개 추출 방법 2

print("아래 문장을 그대로 입력하세요:")
print(target)

input("Press enter to Start.")

start = time.time() # 시작 시간
typed = input() # 사용자가 타이핑 한 내용
end = time.time() # 종료 시간

elapsed = format(end-start, ".3f") # 걸린 시간

# 정확도 계산
#  zip() : 길이가 다르면 짧은 쪽 기준
'''정확한 문자 개수를 세는 코드'''
# for a,b in zip(target, typed): # target에서 나온건 a에 type에서 나온건 b에
    # if a==b :
    #     correct_chars += 1 # 방법 1
correct_chars = sum(1 for a,b in zip(target, typed) if a==b ) # 방법 2

'''정확도'''
accuracy = correct_chars / len(target) * 100
accuracy = format(accuracy, ".1f") 

'''삽입'''
sql = "insert into typing_records(elapsed,accuracy) values(:1,:2)"
cursor.execute(sql,(elapsed,accuracy)) # with구문 없이 열고
conn.commit()

cursor.close() # with구문 없이 닫아여
conn.close




# 테이블생성 : typing_records()


# sectences 문장 중 임의의 문장을 출제후 사용자가 타이핑하는 시간을 잰 후 저장
# 정확도 계산 like 몇 퍼센트냐~ / 문자 단위로 계산


# 걸린 시간, 정확도율, 날짜